version: "3.9"
services:
  ddddocrdemo:
    image: luxiang0412/ddddocrdemo:latest
    container_name: ddddocrdemo
    restart: always
    ports:
      - "5000:5000"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - ddddocrdemo_network
    command: ["flask", "--app", "main", "run", "-h", "0.0.0.0"]
networks:
  ddddocrdemo_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
